# Upload the WebP animations in output/ as assets on the `readme-assets` release.
# --clobber keeps the releases/download URLs stable, so the README and the
# gallery issue keep working without edits after a re-record.
$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

$tag = 'readme-assets'
$files = Get-ChildItem output\*.webp
if (-not $files) { throw 'No WebP files in output\ - run record-all.ps1 first.' }

gh release view $tag | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Host "Creating $tag release..." -ForegroundColor Cyan
    gh release create $tag --title 'README demo assets' --prerelease --latest=false `
        --notes 'Storage tag for the demo animations embedded in the README. Regenerated by demos/record-all.ps1 + publish.ps1 (local-only folder, see the gallery issue).'
    if ($LASTEXITCODE -ne 0) { throw 'Failed to create release.' }
}

gh release upload $tag @($files.FullName) --clobber
if ($LASTEXITCODE -ne 0) { throw 'Upload failed.' }

$repo = gh repo view --json nameWithOwner -q .nameWithOwner
Write-Host "`nUploaded. Stable URLs:" -ForegroundColor Green
foreach ($file in $files) {
    "https://github.com/$repo/releases/download/$tag/$($file.Name)"
}
